//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayHocTrucTuyen
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauHoiBaoMat
    {
        public int STT { get; set; }
        public string Ma_Phong { get; set; }
        public string Cau_Hoi { get; set; }
        public string Loi_Giai { get; set; }
        public string Dap_An { get; set; }
    
        public virtual PhongThi PhongThi { get; set; }
    }
}
