//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayHocTrucTuyen
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocSinhThuocLop
    {
        public string Ma_ND { get; set; }
        public string Ma_Lop { get; set; }
        public Nullable<System.DateTime> Ngay_Tham_Gia { get; set; }
    
        public virtual LopHoc LopHoc { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
