//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayHocTrucTuyen
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DayHocTrucTuyenEntities : DbContext
    {
        public DayHocTrucTuyenEntities()
            : base("name=DayHocTrucTuyenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaiDang> BaiDangs { get; set; }
        public virtual DbSet<BaoCao> BaoCaos { get; set; }
        public virtual DbSet<BiCamThi> BiCamThis { get; set; }
        public virtual DbSet<BinhLuan> BinhLuans { get; set; }
        public virtual DbSet<CamXuc> CamXucs { get; set; }
        public virtual DbSet<CauHoiBaoMat> CauHoiBaoMats { get; set; }
        public virtual DbSet<CauHoiThi> CauHoiThis { get; set; }
        public virtual DbSet<CauTraLoi> CauTraLois { get; set; }
        public virtual DbSet<DanhGiaLop> DanhGiaLops { get; set; }
        public virtual DbSet<Ghim> Ghims { get; set; }
        public virtual DbSet<HocSinhThuocLop> HocSinhThuocLops { get; set; }
        public virtual DbSet<LoaiND> LoaiNDs { get; set; }
        public virtual DbSet<LopHoc> LopHocs { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<PhieuDanhGia> PhieuDanhGias { get; set; }
        public virtual DbSet<PhongThi> PhongThis { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<ThichTrang> ThichTrangs { get; set; }
        public virtual DbSet<ThoiGianLamBai> ThoiGianLamBais { get; set; }
        public virtual DbSet<ThongBao> ThongBaos { get; set; }
        public virtual DbSet<TinNhan> TinNhans { get; set; }
        public virtual DbSet<XemTrang> XemTrangs { get; set; }
    }
}
