//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayHocTrucTuyen
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ThichTrang
    {
        public string Ma_YT { get; set; }
        public string Nguoi_Dung { get; set; }
        public string Nguoi_Thich { get; set; }
        public System.DateTime Thoi_Gian { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }

        DayHocTrucTuyenEntities db = new DayHocTrucTuyenEntities();
        public string setMa(string nd)
        {
            ThichTrang yt = db.ThichTrangs.Where(x => x.Nguoi_Dung == nd).OrderByDescending(x => x.Ma_YT).FirstOrDefault();
            if (yt == null)
            {
                return nd + "_0000001";
            }
            int temp = int.Parse(Convert.ToString(yt.Ma_YT).Substring(8));
            string ma_xt = nd + "_" + Convert.ToString(10000000 + temp + 1).Substring(1);
            return ma_xt;
        }
    }
}
