//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayHocTrucTuyen
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ThongBao
    {
        public string Ma_TB { get; set; }
        public string Ma_ND { get; set; }
        public string Tieu_De { get; set; }
        public string Noi_Dung { get; set; }
        public System.DateTime Thoi_Gian { get; set; }
        public bool Trang_Thai { get; set; }
        public string Lien_Ket { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }

        DayHocTrucTuyenEntities db = new DayHocTrucTuyenEntities();

        public ThongBao() { }
        public ThongBao(string ma_ND)
        {
            this.Ma_ND = ma_ND;
        }

        public string setMa(string maND)
        {
            var tb = db.ThongBaos.Where(x => x.Ma_ND == maND);
            if (tb.Count() == 0) return "00001";

            string ma = Convert.ToString(100000 + tb.Count() + 1).Substring(1);
            return ma;
        }
        public List<ThongBao> getAllThongBao()
        {
            var tb = db.ThongBaos.Where(x => x.Ma_ND == this.Ma_ND).OrderByDescending(x => x.Thoi_Gian).ToList();
            return tb;
        }
        public List<ThongBao> getThongBaoChuaXem()
        {
            var tb = db.ThongBaos.Where(x => x.Ma_ND == this.Ma_ND && x.Trang_Thai == false).OrderByDescending(x => x.Thoi_Gian).ToList();
            return tb;
        }
        public List<ThongBao> getThongBaoDaXem()
        {
            var tb = db.ThongBaos.Where(x => x.Ma_ND == this.Ma_ND && x.Trang_Thai == true).OrderByDescending(x => x.Thoi_Gian).ToList();
            return tb;
        }
        public int getSLThongBao()
        {
            return db.ThongBaos.Where(x => x.Ma_ND == this.Ma_ND).Count();
        }
        public int getSLThongBaoChuaXem()
        {
            return db.ThongBaos.Where(x => x.Ma_ND == this.Ma_ND && x.Trang_Thai == false).Count();
        }
        public int getSLThongBaoDaXem()
        {
            return db.ThongBaos.Where(x => x.Ma_ND == this.Ma_ND && x.Trang_Thai == true).Count();
        }
    }
}
