//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayHocTrucTuyen
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class TinNhan
    {
        public int ID { get; set; }
        public string Nguoi_Gui { get; set; }
        public string Nguoi_Nhan { get; set; }
        public System.DateTime Thoi_Gian { get; set; }
        public string Noi_Dung { get; set; }
        public bool Trang_Thai { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }

        DayHocTrucTuyenEntities db = new DayHocTrucTuyenEntities();

        public int setID()
        {
            var tn = db.TinNhans.OrderByDescending(x => x.ID).FirstOrDefault();
            return tn.ID + 1;
        }
        public List<TinNhan> getTinNhanChuaXem(string maND)
        {
            var tn = db.TinNhans.Where(x => x.Nguoi_Nhan == maND && x.Trang_Thai == false).ToList();
            List<TinNhan> list = new List<TinNhan>();
            for(int i = 0; i < tn.Count; i++)
            {
                list.Add(tn[i]);
                if (i > 0 && tn[i - 1].Nguoi_Gui == tn[i].Nguoi_Gui)
                {
                    list.Remove(tn[i - 1]);
                }
            }

            return list;
        }
        public int getSLTinNhanChuaXem(string maND)
        {
            var tn = db.TinNhans.Where(x => x.Nguoi_Nhan == maND && x.Trang_Thai == false).ToList();
            int dem = 0;
            for(var i = 0; i < tn.Count; i++)
            {
                dem++;
                if(i > 0 && tn[i-1].Nguoi_Gui == tn[i].Nguoi_Gui)
                {
                    dem--;
                }
            }

            return dem;
        }
        public NguoiDung getUser(string maND)
        {
            var nd = db.NguoiDungs.FirstOrDefault(x => x.Ma_ND == maND);
            nd.SDT = null;
            nd.Email = null;
            nd.Mat_Khau = null;
            nd.Img_Nhan_Dien = null;

            return nd;
        }
        public List<TinNhan> getTinNhanTuUser(string nguoigui, string nguoinhan)
        {
            var tn = db.TinNhans.Where(x => x.Nguoi_Gui == nguoigui && x.Nguoi_Nhan == nguoinhan).OrderBy(x => x.Thoi_Gian);
            return tn.ToList();
        }
        public List<TinNhan> getAllTinNhan(string user1, string user2)
        {
            List<TinNhan> tinNhans = new List<TinNhan>();
            var tn1 = db.TinNhans.Where(x => x.Nguoi_Gui == user1 && x.Nguoi_Nhan == user2);
            var tn2 = db.TinNhans.Where(x => x.Nguoi_Gui == user2 && x.Nguoi_Nhan == user1);
            tinNhans.AddRange(tn1);
            tinNhans.AddRange(tn2);

            return tinNhans.OrderBy(x => x.Thoi_Gian).ToList();
        }
    }
}
